language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.2
    - 7.3
    - 7.4

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - composer test
